import React, { useState } from 'react';
import { View, ScrollView, StyleSheet, Alert } from 'react-native';
import { Text, Button } from '@mockly/design-system';
import {
  SubscriptionPlan,
  BillingCycle,
  SubscriptionPayment,
} from '@mockly/entities';
import { SubscriptionService, ApiClient } from '@mockly/api';
import {
  SubscriptionPlanCard,
  PlanOption,
} from '../components/SubscriptionPlanCard';
import { LoadingState } from '../components/LoadingState';

// TODO: Replace with actual API configuration
const apiClient = new ApiClient({ baseURL: 'https://api.mockly.example.com' });
const subscriptionService = new SubscriptionService(apiClient);

// Sample plan options - in a real app, these would come from the API
const planOptions: PlanOption[] = [
  {
    plan: SubscriptionPlan.BASIC,
    billingCycle: BillingCycle.MONTHLY,
    price: 9.99,
    currency: 'USD',
    features: [
      'Up to 10 projects',
      'Basic support',
      '5GB storage',
      'API access',
    ],
  },
  {
    plan: SubscriptionPlan.BASIC,
    billingCycle: BillingCycle.YEARLY,
    price: 99.99,
    currency: 'USD',
    features: [
      'Up to 10 projects',
      'Basic support',
      '5GB storage',
      'API access',
      'Save 16%',
    ],
  },
  {
    plan: SubscriptionPlan.PREMIUM,
    billingCycle: BillingCycle.MONTHLY,
    price: 29.99,
    currency: 'USD',
    features: [
      'Unlimited projects',
      'Priority support',
      '50GB storage',
      'Advanced API access',
      'Custom integrations',
    ],
  },
  {
    plan: SubscriptionPlan.PREMIUM,
    billingCycle: BillingCycle.YEARLY,
    price: 299.99,
    currency: 'USD',
    features: [
      'Unlimited projects',
      'Priority support',
      '50GB storage',
      'Advanced API access',
      'Custom integrations',
      'Save 16%',
    ],
  },
];

export interface SubscriptionPaymentScreenProps {
  onPaymentSuccess?: () => void;
  onPaymentFailure?: (error: string) => void;
}

export const SubscriptionPaymentScreen: React.FC<
  SubscriptionPaymentScreenProps
> = ({ onPaymentSuccess, onPaymentFailure }) => {
  const [selectedOption, setSelectedOption] = useState<PlanOption | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);

  const handleSelectPlan = (option: PlanOption) => {
    setSelectedOption(option);
  };

  const handlePayment = async () => {
    if (!selectedOption) {
      Alert.alert('Error', 'Please select a subscription plan');
      return;
    }

    setIsProcessing(true);

    try {
      // Step 1: Initiate payment
      const paymentData: SubscriptionPayment = {
        subscriptionId: '', // Will be generated by server
        plan: selectedOption.plan,
        billingCycle: selectedOption.billingCycle,
        amount: selectedOption.price,
        currency: selectedOption.currency,
      };

      const paymentRequest =
        await subscriptionService.initiateSubscriptionPayment(paymentData);

      // Step 2: In a real app, this would integrate with Iamport SDK
      // For now, we'll simulate a successful payment
      // Import Iamport and call IMP.request_pay() here
      // Example:
      // IMP.request_pay({
      //   ...paymentRequest,
      // }, async (response) => {
      //   // Handle Iamport response
      // });

      // Simulating payment success for demonstration
      const mockIamportResponse = {
        success: true,
        imp_uid: 'imp_' + Date.now(),
        merchant_uid: paymentRequest.merchant_uid,
      };

      // Step 3: Complete payment on server
      const result =
        await subscriptionService.completeSubscriptionPayment(
          mockIamportResponse,
        );

      if (result.success) {
        Alert.alert('Success', 'Subscription activated successfully!', [
          {
            text: 'OK',
            onPress: () => onPaymentSuccess?.(),
          },
        ]);
      } else {
        throw new Error(result.error || 'Payment failed');
      }
    } catch (error) {
      const errorMessage =
        error instanceof Error ? error.message : 'Payment failed';
      Alert.alert('Payment Failed', errorMessage, [
        {
          text: 'OK',
          onPress: () => onPaymentFailure?.(errorMessage),
        },
      ]);
    } finally {
      setIsProcessing(false);
    }
  };

  if (isProcessing) {
    return <LoadingState message="Processing payment..." />;
  }

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text variant="h2" style={styles.title}>
          Choose Your Plan
        </Text>
        <Text variant="body" style={styles.subtitle}>
          Select a subscription plan that fits your needs
        </Text>
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.planList}
      >
        {planOptions.map((option, index) => (
          <SubscriptionPlanCard
            key={index}
            option={option}
            selected={selectedOption === option}
            onSelect={handleSelectPlan}
          />
        ))}
      </ScrollView>

      <View style={styles.footer}>
        <Button
          onPress={handlePayment}
          disabled={!selectedOption || isProcessing}
          style={styles.payButton}
        >
          {selectedOption
            ? `Subscribe for ${selectedOption.currency} ${selectedOption.price}`
            : 'Select a Plan'}
        </Button>
        <Text variant="caption" style={styles.disclaimer}>
          By subscribing, you agree to our Terms of Service and Privacy Policy
        </Text>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  title: {
    marginBottom: 8,
  },
  subtitle: {
    color: '#666',
  },
  scrollView: {
    flex: 1,
  },
  planList: {
    padding: 16,
  },
  footer: {
    padding: 16,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  payButton: {
    marginBottom: 12,
  },
  disclaimer: {
    textAlign: 'center',
    color: '#999',
  },
});
